#!/bin/bash

#Extracción del cromosoma 10
for i in $(ls $1/*.bam); do name=$(echo $i | cut -d "_" -f 1,2,3); samtools index $i; samtools view -h -b $i > "$name"".bam"

#Conversión a fastq
samtools bam2fq SAMPLE.bam > SAMPLE.fastq #Converts the .bam into .fastq
# extracting reads ending with '/1' or '/2'
cat SAMPLE.fastq | grep '^@.*/1$' -A 3 --no-group-separator > SAMPLE_R1.fastq
cat SAMPLE.fastq | grep '^@.*/2$' -A 3 --no-group-separator > SAMPLE_R2.fastq

#Creating fastqc files from the extracted reads
fastqc -o fastqc ~/Maize_Gen50x/Chr10/*_R*.fastq

#Trimming of sequences ussing Trimmomatic
java -jar ~/Programs/Trimmomatic-0.39/trimmomatic-0.39.jar PE -threads 10 -phred33 -basein input.fq -baseout output.fq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

#Creating index from reference genome
bwa index ref.fals

#Aligning to reference genome using BWA mem (PE)
bwa mem -t 10 -M -R '@RG\tID:NRGENE\tSM:PE0346\tPL:PE\tLB:no\tPU:unit1' ~/Maize_RefGen/MaskedDNA/Zea_mays.AGPv4.dna_rm.chromosome.10.fa.gz ~/FiltradoTRIM/PE0346_Ch10FP_1P.fq.gz ~/FiltradoTRIM/PE0346_Ch10FP_2P.fq.gz > PE0346_Ch10_PE.sam

#Aligning to reference genome using BWA mem (SE)
bwa mem -t 10 -M -R '@RG\tID:NRGENE\tSM:PE0346\tPL:SE\tLB:no\tPU:unit1' ~/Maize_RefGen/MaskedDNA/Zea_mays.AGPv4.dna_rm.chromosome.10.fa.gz ~/FiltradosTRIM/PE0346_Ch10FP_1U.fq.gz > PE0346_Ch10_SE.sam

#Sorting sam file and converting to bam with Picard (PE)
java -Xmx20g -XX:ParallelGCThreads=10 -jar Programs/PicardTools/picard.jar SortSam MAX_RECORDS_IN_RAM=2000000 INPUT=PE0346_Ch10_PE.sam OUTPUT="PE0346_Ch10_PE_sorted.bam" SORT_ORDER=coordinate

#Sorting sam file and converting to bam with Picard (PE)
java -Xmx20g -XX:ParallelGCThreads=10 -jar Programs/PicardTools/picard.jar SortSam MAX_RECORDS_IN_RAM=2000000 INPUT=PE0346_Ch10_PE.sam OUTPUT="PE0346_Ch10_PE_sorted.bam" SORT_ORDER=coordinate

#Merging data using samtools

for i in $(ls *bam | awk -F "_" '{print $1}' | uniq);do ls $i*.bam > "$i"."txt"  ; done

for i in $(ls *txt); do nombre=$(echo $i | awk -F "." '{print $1}'); samtools merge "$nombre""_merged.bam" -b $i; done

#	Remove duplicates using picard tools
java -Xmx20g -XX:ParallelGCThreads=10 -jar Programs/PicardTools/picard.jar MarkDuplicates INPUT=PE0346_merged.bam OUTPUT=PE0346_dedup.bam REMOVE_DUPLICATES=true METRICS_FILE=PE0346_metrics.txt

#	Create index using picard tools
java -Xmx20g -XX:ParallelGCThreads=10 -jar Programs/PicardTools/picard.jar BuildBamIndex INPUT=PE0346_dedup.bam

#	Indel realignment using GATK
java -Xmx20g -jar ~/Programs/gatk-4.1.4.0/gatk-package-4.1.4.0-local.jar -T RealignerTargetCreator -R ~/Maize_RefGen/MaskedDNA/Zea_mays.AGPv4.dna_rm.chromosome.10.fa.gz -I PE0346_dedup.bam -o PE00346-forIndelRealigner.intervals


